#!/bin/bash

service="service1 service2 service3"

for i in $service
do
   ps -ef | grep "$i" 
   if [ $? -ne 0 ];then
    mail -s "process stopped. pls take appropriacte action" abc@gmail.com
   fi
done
