#!/bin/bash

echo "Enter the name of file"
read name

find /home/ec2-user/ -iname $name  > log1

if [ -s $name  ];then
echo "The files found in the path :"
cat log1
else
echo "The file does not exist"
fi
rm log1
